---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: slo-burndown-dashboard
    files:
      - slo-burndown-dashboard.json=dashboards/slo-burndown.json
    options:
      labels:
        app: kube-prometheus-stack-grafana
        grafana_dashboard: "1"
      annotations:
        argocd.argoproj.io/sync-wave: "5"
  - name: cilium-agent-metrics-dashboard
    files:
      - cilium-agent-metrics-dashboard.json=dashboards/cilium-agent-metrics.json
    options:
      labels:
        app: kube-prometheus-stack-grafana
        grafana_dashboard: "1"
      annotations:
        argocd.argoproj.io/sync-wave: "5"
