apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.ingress.tlsSecret }}
  duration: "2160h"
  renewBefore: "720h"
  commonName: {{ index .Values.ingress.hosts 0 }}
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - digital signature
    - key encipherment
  issuerRef:
    name: cledyu-ca
    kind: ClusterIssuer
    group: cert-manager.io
