installCRDs: true

serviceAccount:
  create: true
  name: eso-controller

resources:
  requests:
    cpu: 50m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault
