---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://airflow.apache.org/
      chart: airflow
      targetRevision: 1.15.0
      helm:
        releaseName: airflow
        valueFiles:
          - $values/gitops/apps/airflow/values.yaml
    - repoURL: https://github.com/requset700k/Cledyu.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/requset700k/Cledyu.git
      targetRevision: main
      path: gitops/apps/airflow
      directory:
        include: "*.yaml"
        exclude: "values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
