apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-backup-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/requset700k/Cledyu.git
    targetRevision: main
    path: gitops/apps/backup-secrets
    helm:
      releaseName: backup-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
