---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 0.12.5
      helm:
        releaseName: alloy
        valueFiles:
          - $values/gitops/apps/alloy/values.yaml
    - repoURL: https://github.com/requset700k/Cledyu.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
