---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
  endpoints:
    - port: tcp-prometheus-servicemonitor
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true # cert-manager가 붙이는 namespace/name 레이블 보존
