---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook-certmanager
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alertmanager-discord-webhook-certmanager
  data:
    - secretKey: webhook-url
      remoteRef:
        key: alerts/cert-manager
        property: discord_webhook_url
