apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dr-heartbeat-creds
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dr-heartbeat-creds
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.vaultKey }}
        property: access_key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: {{ .Values.vaultKey }}
        property: secret_access_key
