---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-ui-oidc
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafka-ui-oidc
  data:
    - secretKey: client-secret
      remoteRef:
        key: oidc/kafka-ui
        property: client_secret
