---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-ui-oidc
  namespace: kafka
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafka-ui-oidc
  data:
    - secretKey: client-secret
      remoteRef:
        key: oidc/kafka-ui
        property: client_secret
